### PR TITLE
Update gui.cs

### LINKED ISSUE #71: Support multi-select editing
Using space, we can select multiple steps. it'd be nice if that could be used to edit multiple steps at the same time.

### PR DESCRIPTION
**Pull request by frederikja163**
Close #71

### CODE REVIEW

**Comment by StefanHolst** [comment]
It seems macos does not work with the ALT key. @alnlarsen I think we need your help to find a good solution for this.

**Comment by frederikja163** [comment]
> It seems macos does not work with the ALT key. @alnlarsen I think we need your help to find a good solution for this.

This is also repoted in #9

**Comment by rmadsen-ks** [comment]
- CTRL + N -> F2
- CTRL + Shift + N -> F3

- Helper buttons not available after exiting settings
- Expands expandable test steps after adding them to the plan.
- Error after moving steps with no steps selected:
```
2022-08-26 12:37:30.732452 ; TUI            ; Error       ; See session log for more information.
2022-08-26 12:37:30.742765 ; TUI            ; Debug       ; NullReferenceException: Object reference not set to an instance of an object.
2022-08-26 12:37:30.751747 ; TUI            ; Debug       ;     at OpenTap.Tui.Views.TestPlanView.KeyMoveStep(KeyEventEventArgs kbEvent) in /home/romadsen/code/opentap-tui/OpenTAP.TUI/Views/TestPlanView.cs:line 181
2022-08-26 12:37:30.751754 ; TUI            ; Debug       ;     at Terminal.Gui.View.ProcessHotKey(KeyEvent keyEvent) in /home/romadsen/code/opentap-tui/gui.cs/Terminal.Gui/Core/View.cs:line 1873
2022-08-26 12:37:30.751756 ; TUI            ; Debug       ;     at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke) in /home/romadsen/code/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 420
2022-08-26 12:37:30.751759 ; TUI            ; Debug       ;     at Terminal.Gui.CursesDriver.ProcessInput(Action`1 keyHandler, Action`1 keyDownHandler, Action`1 keyUpHandler, Action`1 mouseHandler) in /home/romadsen/code/opentap-tui/gui.cs/Terminal.Gui/ConsoleDrivers/CursesDriver/CursesDriver.cs:line 790
2022-08-26 12:37:30.751761 ; TUI            ; Debug       ;     at Terminal.Gui.CursesDriver.<>c__DisplayClass62_0.<PrepareToRun>b__0(MainLoop x) in /home/romadsen/code/opentap-tui/gui.cs/Terminal.Gui/ConsoleDrivers/CursesDriver/CursesDriver.cs:line 817
2022-08-26 12:37:30.751764 ; TUI            ; Debug       ;     at Terminal.Gui.UnixMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration() in /home/romadsen/code/opentap-tui/gui.cs/Terminal.Gui/ConsoleDrivers/CursesDriver/UnixMainLoop.cs:line 229
2022-08-26 12:37:30.751767 ; TUI            ; Debug       ;     at Terminal.Gui.MainLoop.MainIteration() in /home/romadsen/code/opentap-tui/gui.cs/Terminal.Gui/Core/MainLoop.cs:line 295

```

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]
I had a few comments to this.

**Review by rmadsen-ks — APPROVED** [review]
Seems to work well! Lets merge!

**Pull request merged**
